services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aibot:latest
    depends_on:
      - postgres
    env_file: .env
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aibot_db
      POSTGRES_USER: aibot
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

