token: 1234567890:qwertyuio-pasdfghjklzxcvbnmqwertyui
username: artific_intellig_bot
creatorId: 1234567890
fileIdGifChatLoading: CgACAgIAAx0EQu_s8gABOBeZZLG-21LgrDNNzv87mI3JaDrqfIAAAjcrAAIB4pFJeY80OYWR8-8vBA